# Use postgres/example user/password credentials
version: '3.8'

services:
  core-api:
    build:
      context: .
      dockerfile: ./Dockerfiles/Application/Dockerfile
    ports:
      - '8090:8090'
    volumes:
      #- {replace with your ssh key directory}:/home/node/.ssh:ro
      - .:/srv/core_api
      - /srv/core_api/node_modules
    command: bash -c "npm run migrate && npm run start"
